"""added artifact_tables

Revision ID: a7151cecb205
Revises: baaa94ff40c9
Create Date: 2024-07-17 15:01:20.766228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'a7151cecb205'
down_revision: Union[str, None] = 'baaa94ff40c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION if not exists postgis;')
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('SIMPLE', 'O_MAP', name='artifactkind'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('competition', sa.Integer(), nullable=True),
    sa.Column('uploader', sa.Integer(), nullable=True),
    sa.Column('upload_ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['uploader'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name', 'competition', name='artifact_unique_constraint')
    )
    op.create_index(op.f('ix_artifact_id'), 'artifact', ['id'], unique=False)
    op.create_table('o_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_point', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['artifact'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_name', 'location_name', name='o_maps_unique_constraint')
    )
    # op.create_index('idx_o_maps_location_point', 'o_maps', ['location_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_o_maps_id'), 'o_maps', ['id'], unique=False)
    op.drop_constraint('workout_unique_constraint', 'workouts', type_='unique')
    op.create_unique_constraint('workout_unique_constraint', 'workouts', ['date', 'sport_kind', 'user', 'competition'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workout_unique_constraint', 'workouts', type_='unique')
    op.create_unique_constraint('workout_unique_constraint', 'workouts', ['date', 'sport_kind', 'user'])
    op.drop_index(op.f('ix_o_maps_id'), table_name='o_maps')
    op.drop_index('idx_o_maps_location_point', table_name='o_maps', postgresql_using='gist')
    op.drop_table('o_maps')
    op.drop_index(op.f('ix_artifact_id'), table_name='artifact')
    op.drop_table('artifact')
    op.execute('drop extension postgis cascade;')
    # ### end Alembic commands ###
