version: "3.9"
services:
  postgres:
    image: postgis/postgis:15-3.4
    env_file:
      - ../packages/postgres/.env
    volumes:
      - ../packages/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U split_pg_user -d split_pg_pswd"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../packages/minio/.env
    volumes:
      - ../packages/minio/data:/data
    command: server /data --console-address ":9001"
