"""add start_time to competitions

Revision ID: 0242cc8739e0
Revises: 34aa6e2312da
Create Date: 2026-03-01 21:33:17.181447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0242cc8739e0'
down_revision: Union[str, None] = '34aa6e2312da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'start_time')
    # ### end Alembic commands ###
