"""init migration

Revision ID: 34aa6e2312da
Revises:
Create Date: 2026-02-23 14:28:53.147291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '34aa6e2312da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define all enum types used across multiple tables
gender_enum = postgresql.ENUM('MALE', 'FEMALE', name='gender', create_type=False)
privacy_enum = postgresql.ENUM('PUBLIC', 'PRIVATE', 'FOLLOWERS', 'BY_REQUEST', name='privacy', create_type=False)
accounttype_enum = postgresql.ENUM('REGISTERED', 'GHOST', name='accounttype', create_type=False)
sportkind_enum = postgresql.ENUM('ORIENT', 'RUN', 'BIKE', 'CXSKI', 'ST', name='sportkind', create_type=False)
eventstatus_enum = postgresql.ENUM('DRAFT', 'PLANNED', 'IN_PROGRESS', 'FINISHED', 'CANCELLED', name='eventstatus', create_type=False)
eventformat_enum = postgresql.ENUM('SINGLE', 'MULTI_STAGE', name='eventformat', create_type=False)
followstatus_enum = postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='followstatus', create_type=False)
qualificationtype_enum = postgresql.ENUM('ATHLETE', 'REFEREE', 'COACH', name='qualificationtype', create_type=False)
workoutstatus_enum = postgresql.ENUM('DRAFT', 'PROCESSING', 'READY', 'ERROR', name='workoutstatus', create_type=False)
clubrole_enum = postgresql.ENUM('OWNER', 'COACH', 'MEMBER', name='clubrole', create_type=False)
membershipstatus_enum = postgresql.ENUM('PENDING', 'ACTIVE', 'REJECTED', name='membershipstatus', create_type=False)
claimtype_enum = postgresql.ENUM('EVENT', 'CLUB', name='claimtype', create_type=False)
claimstatus_enum = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='claimstatus', create_type=False)
startformat_enum = postgresql.ENUM('MASS_START', 'SEPARATED_START', 'FREE', name='startformat', create_type=False)
competitionstatus_enum = postgresql.ENUM('PLANNED', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'IN_PROGRESS', 'FINISHED', 'CANCELLED', name='competitionstatus', create_type=False)
eventrole_enum = postgresql.ENUM('ORGANIZER', 'SECRETARY', 'JUDGE', 'VOLUNTEER', 'PARTICIPANT', 'SPECTATOR', name='eventrole', create_type=False)
eventposition_enum = postgresql.ENUM('CHIEF', 'DEPUTY', name='eventposition', create_type=False)
participationstatus_enum = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='participationstatus', create_type=False)
artifactkind_enum = postgresql.ENUM('MAP', 'COURSE', 'RESULTS_FILE', 'PHOTO', 'GPS_TRACK', 'FIT_FILE', 'TCX_FILE', name='artifactkind', create_type=False)
registrationstatus_enum = postgresql.ENUM('PENDING', 'REGISTERED', 'CONFIRMED', 'REJECTED', name='registrationstatus', create_type=False)
controlpointtype_enum = postgresql.ENUM('START', 'CONTROL', 'FINISH', name='controlpointtype', create_type=False)
totalresultstatus_enum = postgresql.ENUM('OK', 'INCOMPLETE', 'DSQ', name='totalresultstatus', create_type=False)
spectatorsource_enum = postgresql.ENUM('WEB', 'MOBILE', 'EMBED', name='spectatorsource', create_type=False)
resultstatus_enum = postgresql.ENUM('OK', 'DSQ', 'DNS', 'DNF', name='resultstatus', create_type=False)

ALL_ENUMS = [
    gender_enum, privacy_enum, accounttype_enum, sportkind_enum,
    eventstatus_enum, eventformat_enum, followstatus_enum, qualificationtype_enum,
    workoutstatus_enum, clubrole_enum, membershipstatus_enum, claimtype_enum,
    claimstatus_enum, startformat_enum, competitionstatus_enum, eventrole_enum,
    eventposition_enum, participationstatus_enum, artifactkind_enum,
    registrationstatus_enum, controlpointtype_enum, totalresultstatus_enum,
    spectatorsource_enum, resultstatus_enum,
]


def upgrade() -> None:
    # Create all enum types first (checkfirst=True prevents "already exists" errors)
    bind = op.get_bind()
    for enum in ALL_ENUMS:
        enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('username_display', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', gender_enum, nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('privacy_default', privacy_enum, nullable=True),
    sa.Column('account_type', accounttype_enum, nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name', 'last_name', 'birthday', name='user_unique_constraint')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('claim_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claimer_id', sa.Integer(), nullable=False),
    sa.Column('ghost_user_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', claimtype_enum, nullable=False),
    sa.Column('status', claimstatus_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claimer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ghost_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_requests_id'), 'claim_requests', ['id'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('privacy', privacy_enum, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('sport_kind', sportkind_enum, nullable=False),
    sa.Column('privacy', privacy_enum, nullable=False),
    sa.Column('event_format', eventformat_enum, nullable=False),
    sa.Column('status', eventstatus_enum, nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('recruitment_open', sa.Boolean(), nullable=False),
    sa.Column('needed_roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'sport_kind', name='event_unique_constraint')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('user_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('status', followstatus_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='user_follow_unique')
    )
    op.create_index(op.f('ix_user_follows_id'), 'user_follows', ['id'], unique=False)
    op.create_table('user_qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', qualificationtype_enum, nullable=False),
    sa.Column('sport_kind', sportkind_enum, nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_qualifications_id'), 'user_qualifications', ['id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sport_kind', sportkind_enum, nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('finish_datetime', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('elevation_gain', sa.Integer(), nullable=True),
    sa.Column('status', workoutstatus_enum, nullable=False),
    sa.Column('privacy', privacy_enum, nullable=False),
    sa.Column('fit_file', sa.String(), nullable=True),
    sa.Column('gpx_file', sa.String(), nullable=True),
    sa.Column('tcx_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.create_table('club_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('role', clubrole_enum, nullable=False),
    sa.Column('status', membershipstatus_enum, nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'club_id', name='club_membership_unique')
    )
    op.create_index(op.f('ix_club_memberships_id'), 'club_memberships', ['id'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sport_kind', sportkind_enum, nullable=True),
    sa.Column('start_format', startformat_enum, nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', competitionstatus_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_table('event_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('role', eventrole_enum, nullable=False),
    sa.Column('position', eventposition_enum, nullable=True),
    sa.Column('competition_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_event_invites_id'), 'event_invites', ['id'], unique=False)
    op.create_table('event_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('role', eventrole_enum, nullable=False),
    sa.Column('position', eventposition_enum, nullable=True),
    sa.Column('status', participationstatus_enum, nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='event_participation_unique')
    )
    op.create_index(op.f('ix_event_participations_id'), 'event_participations', ['id'], unique=False)
    op.create_table('event_total_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_calculate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_total_configs_id'), 'event_total_configs', ['id'], unique=False)
    op.create_table('workout_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('control_point', sa.String(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('cumulative_time', sa.Integer(), nullable=False),
    sa.Column('split_time', sa.Integer(), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'sequence', name='workout_split_unique')
    )
    # Note: spatial index idx_workout_splits_position is auto-created by geoalchemy2
    op.create_index(op.f('ix_workout_splits_id'), 'workout_splits', ['id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', artifactkind_enum, nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(competition_id IS NOT NULL AND workout_id IS NULL) OR (competition_id IS NULL AND workout_id IS NOT NULL)', name='artifact_owner_check'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_table('competition_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('bib_number', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('status', registrationstatus_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'competition_id', name='competition_registration_unique')
    )
    op.create_index(op.f('ix_competition_registrations_id'), 'competition_registrations', ['id'], unique=False)
    op.create_table('competition_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', eventrole_enum, nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'user_id', name='competition_team_unique')
    )
    op.create_index(op.f('ix_competition_teams_id'), 'competition_teams', ['id'], unique=False)
    op.create_table('distances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('climb_meters', sa.Integer(), nullable=True),
    sa.Column('classes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distances_id'), 'distances', ['id'], unique=False)
    op.create_table('event_total_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_overall', sa.Integer(), nullable=True),
    sa.Column('stages_counted', sa.Integer(), nullable=False),
    sa.Column('stages_total', sa.Integer(), nullable=False),
    sa.Column('status', totalresultstatus_enum, nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['event_total_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'user_id', 'class', name='total_result_unique')
    )
    op.create_index(op.f('ix_event_total_results_id'), 'event_total_results', ['id'], unique=False)
    op.create_table('spectator_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('source', spectatorsource_enum, nullable=False),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spectator_sessions_id'), 'spectator_sessions', ['id'], unique=False)
    op.create_table('control_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distance_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', controlpointtype_enum, nullable=False),
    sa.ForeignKeyConstraint(['distance_id'], ['distances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distance_id', 'code', name='cp_code_unique'),
    sa.UniqueConstraint('distance_id', 'sequence', name='cp_sequence_unique')
    )
    op.create_index(op.f('ix_control_points_id'), 'control_points', ['id'], unique=False)
    op.create_table('orient_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_point', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('scale', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_name', 'location_name', name='orient_maps_unique_constraint')
    )
    # Note: spatial index idx_orient_maps_location_point is auto-created by geoalchemy2
    op.create_index(op.f('ix_orient_maps_id'), 'orient_maps', ['id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('distance_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_overall', sa.Integer(), nullable=True),
    sa.Column('time_total', sa.Integer(), nullable=True),
    sa.Column('time_behind_leader', sa.Integer(), nullable=True),
    sa.Column('status', resultstatus_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['distance_id'], ['distances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'competition_id', name='result_unique')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_table('result_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('control_point', sa.String(), nullable=False),
    sa.Column('control_point_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('cumulative_time', sa.Integer(), nullable=False),
    sa.Column('split_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_point_id'], ['control_points.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id', 'sequence', name='result_split_unique')
    )
    op.create_index(op.f('ix_result_splits_id'), 'result_splits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_splits_id'), table_name='result_splits')
    op.drop_table('result_splits')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_orient_maps_id'), table_name='orient_maps')
    op.drop_table('orient_maps')
    op.drop_index(op.f('ix_control_points_id'), table_name='control_points')
    op.drop_table('control_points')
    op.drop_index(op.f('ix_spectator_sessions_id'), table_name='spectator_sessions')
    op.drop_table('spectator_sessions')
    op.drop_index(op.f('ix_event_total_results_id'), table_name='event_total_results')
    op.drop_table('event_total_results')
    op.drop_index(op.f('ix_distances_id'), table_name='distances')
    op.drop_table('distances')
    op.drop_index(op.f('ix_competition_teams_id'), table_name='competition_teams')
    op.drop_table('competition_teams')
    op.drop_index(op.f('ix_competition_registrations_id'), table_name='competition_registrations')
    op.drop_table('competition_registrations')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_workout_splits_id'), table_name='workout_splits')
    op.drop_table('workout_splits')
    op.drop_index(op.f('ix_event_total_configs_id'), table_name='event_total_configs')
    op.drop_table('event_total_configs')
    op.drop_index(op.f('ix_event_participations_id'), table_name='event_participations')
    op.drop_table('event_participations')
    op.drop_index(op.f('ix_event_invites_id'), table_name='event_invites')
    op.drop_table('event_invites')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_club_memberships_id'), table_name='club_memberships')
    op.drop_table('club_memberships')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_user_qualifications_id'), table_name='user_qualifications')
    op.drop_table('user_qualifications')
    op.drop_index(op.f('ix_user_follows_id'), table_name='user_follows')
    op.drop_table('user_follows')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_claim_requests_id'), table_name='claim_requests')
    op.drop_table('claim_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')

    # Drop all enum types
    bind = op.get_bind()
    for enum in reversed(ALL_ENUMS):
        enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
