"""add control_time to distances

Revision ID: 5899f4a63761
Revises: 0242cc8739e0
Create Date: 2026-03-02 01:58:03.000062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5899f4a63761'
down_revision: Union[str, None] = '0242cc8739e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distances', sa.Column('control_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distances', 'control_time')
    # ### end Alembic commands ###
