"""add time_behind_distance_leader to results

Revision ID: 9279ddd40bdf
Revises: 84da714d4057
Create Date: 2026-03-02 10:35:44.904533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9279ddd40bdf'
down_revision: Union[str, None] = '84da714d4057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('time_behind_distance_leader', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'time_behind_distance_leader')
    # ### end Alembic commands ###
