[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["pzverkov <pavelzverkov1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.101.0"
uvicorn = "^0.23.2"
pydantic = "^2.1.1"
sqlalchemy = "^2.0.19"
python-dotenv = "^1.0.0"
loguru = "^0.7.0"
psycopg2 = "^2.9.7"
alembic = "^1.12.0"
jinja2 = "^3.1.2"
watchfiles = "^0.21.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pylint = "^2.17.5"
isort = { version = "=5.0.1", extras = ["pyproject"] }
mypy = "^1.5.1"

[tool.isort]
src_paths = ["matchtv_recommender"]
multi_line_output = 1
force_grid_wrap = 3
ensure_newline_before_comments = "True"
line_length = 88

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
